### ISSUE TITLE
Default scripts

### ISSUE THREAD

**Issue by artemnovichkov** [swift-xcode/xcodeproj#30]
I released [Carting](https://github.com/artemnovichkov/Carting) for adding and updating Carthage script. There are a few scripts using in almost every project, for example, Fabric, Carthage and SwiftLint. What do you think about adding of default scripts for your framework? And maybe I can help you with it.

**Comment by pepibumur** [comment]
Hey @artemnovichkov!
I just checked Carting but I'm not sure if I get the purpose of it. Could you give me some hints about how it'd integrate with xcodeproj?
Thanks for the idea 😛

**Comment by artemnovichkov** [comment]
Carting automatically adds a script like: 
![screen shot 2017-08-01 at 15 05 42](https://user-images.githubusercontent.com/5051597/28817752-04a7f2c2-76cb-11e7-9a37-98fa30d6b974.png)
Maybe it will be useful to add common used scripts to xcodeproj

**Comment by pepibumur** [comment]
But xcodeproj doesn't use/support Carthage. How would that be integrated?

**Comment by artemnovichkov** [comment]
It's not necessary. xcodeproj will add only `/usr/local/bin/carthage copy-frameworks` to a new script with correct paths. Just like Carting

**Comment by pepibumur** [comment]
Hey @artemnovichkov, I'm still struggling to understand how Carting would integrate with xcodeproj. Carting is a command line tool that developers use to not have to manually add the Carthage script step. I think I'm missing something here.

**Comment by pepibumur** [comment]
I'll close this for now until there's more input to proceed with it.

**Comment by artemnovichkov** [comment]
Nevermind, it were just my thoughts.

**Comment by pepibumur** [comment]
I'd love to understand how we could bring Carting into the project.

**Comment by yonaskolb** [comment]
It sounds like it would be more something that goes into a tool like https://github.com/swift-xcode/xcode, which is what carting is.

In my opinion xcodeproj should be a repo just for reading, modifying and writing xcode project files. Any other functionality would go into tools that use xcodeproj

**Comment by pepibumur** [comment]
That was my understanding. As @yonaskolb pointed out, xcodeproj just provides the models to interact with your Xcode projects. Carting could fit with tools that do some automation in the Carthage area.

**Comment by artemnovichkov** [comment]
I’m not talking about Carting or Carthage, it was just an example. My main idea is that you might implement default scripts in xcodeproj to reduce repetitive actions. For instance, I add a script that increment build number in my every project. And I don’t want to write this script again and again, I want to call `xcodeproj.addAwesomeScript()` and vuala - the script was added. That’s all, and sorry for my English 😀

**Comment by pepibumur** [comment]
Yeah that's the idea @artemnovichkov. We actually started working on that sort of automation in this project https://github.com/swift-xcode/xcode. You are more than welcome to contribute.

**Comment by artemnovichkov** [comment]
Looks interesting, I'm ready to start. Where is a start point? :)

**Comment by pepibumur** [comment]
Can you email me your email and I'll invite you to Slack?

**Comment by artemnovichkov** [comment]
Sure! novichkoff93@gmail.com
