### ISSUE TITLE
Adding files to a PBXGroup

### ISSUE THREAD

**Issue by Daltron** [swift-xcode/xcodeproj#57]
#43 Greatly clarified how to create a new group and add it to an already existing group. However, I am now very uncertain on how to add actual source code files (that are already created) to a group. Is `PBXFileElement` the object I should be using or is there something else? Any help would be appreciated!

Thanks! 👍

**Comment by yonaskolb** [comment]
Hi @Daltron 
You would need a to create a `PBXFileElement` for each file, a `PBXBuildFile` that references that file for each target it should be added to, and then add those `PBXBuildFile` references to the `PBXSourcesBuildPhase` for each target.

That's really getting into the weeds there. Usually tools would be built on top of xcodeproj to achieve things like the above. Tools like https://github.com/yonaskolb/XcodeGen and https://github.com/swift-xcode/xcode

What's your exact use case? Maybe it can be added to one of those tools. Just adding a folder of files to a target?

**Comment by Daltron** [comment]
@yonaskolb Thanks for the detailed response. But yes, that is pretty much exactly my use case. I am wanting to add a group of files to a target. I'll tinker around and see if I can it to do what I want to do. Thanks!
