### ISSUE TITLE
PBXReferenceProxy Support

### ISSUE THREAD

**Issue by artemnovichkov** [swift-xcode/xcodeproj#78]
## Context
I tried to parse my project that contains multiple projects for downloadable IAPs

## What
Simple initialization:
```swift
let project = try XcodeProj(path: "ProjectName.xcodeproj")
```
`PBXReferenceProxy` section:
```
/* Begin PBXReferenceProxy section */
		2E12F4BE1F6665C800E994A6 /* iap2 */ = {
			isa = PBXReferenceProxy;
			fileType = folder;
			path = iap2;
			remoteRef = 2E12F4BD1F6665C800E994A6 /* PBXContainerItemProxy */;
			sourceTree = BUILT_PRODUCTS_DIR;
		};
		2E2578961F6281A20080638D /* unlock.all */ = {
			isa = PBXReferenceProxy;
			fileType = folder;
			path = unlock.all;
			remoteRef = 2E2578951F6281A20080638D /* PBXContainerItemProxy */;
			sourceTree = BUILT_PRODUCTS_DIR;
		};
		2E2A42AF1F613B6000330926 /* iap */ = {
			isa = PBXReferenceProxy;
			fileType = folder;
			path = iap;
			remoteRef = 2E2A42AE1F613B6000330926 /* PBXContainerItemProxy */;
			sourceTree = BUILT_PRODUCTS_DIR;
		};
/* End PBXReferenceProxy section */
```
Related to the error: `The element PBXReferenceProxy is not supported`
## Proposal
I know that it's a rare case, but anyway 🤷‍♂️

**Comment by pepibumur** [comment]
@artemnovichkov, could you attach in this issue the element `PBXReferenceProxy`. I'd like to see the structure of it to add support for it. Thanks 😛

**Comment by artemnovichkov** [comment]
I've updated the description with needed section

**Comment by pepibumur** [comment]
Cool, thanks @artemnovichkov

**Comment by artemnovichkov** [comment]
You missed parsing of `PBXReferenceProxy` objects in `PBXObject.parse(reference:dictionary:)`. Please, add the following code:
```swift
case PBXReferenceProxy.isa:
    return try PBXReferenceProxy(reference: reference, dictionary: dictionary)
```
Why I don't have a permission to push in this branch?..
