### ISSUE TITLE
Error in empty project

### ISSUE THREAD

**Issue by artemnovichkov** [swift-xcode/xcodeproj#80]
## Context
I tried to parse empty project (Xcode 8 or 9 generated).

## What
Simple initialization:
```swift
let project = try XcodeProj(path: "ProjectName.xcodeproj")
```
Related to the error: `[UnboxError] An error occurred while unboxing path "defaultConfigurationName": The key "defaultConfigurationName" is missing.
`

**Comment by pepibumur** [comment]
We can fix it by just updating `XCConfigurationList` to make `defaultConfigurationName` optional. Would you like to work on this issue @artemnovichkov?

**Comment by artemnovichkov** [comment]
Sure, it will be simple task and good point to start.

**Comment by artemnovichkov** [comment]
Really strange, but I haven't this error on another Mac... Will check it tomorrow after Xcode 9 release 🎉

**Comment by pepibumur** [comment]
Cool. Make sure that the project that you are using is the same. Opening the project with different versions of Xcode might introduce some changes in the structure of the project.

**Comment by artemnovichkov** [comment]
I've checked it with Xcode 9 project, everything works without errors 🤷‍♂️.

**Comment by pepibumur** [comment]
I'll check it again from my side and see if there's something missing :/

**Comment by pepibumur** [comment]
I'll close it for now @artemnovichkov. If you come across the same issue, feel free to re-open it.
