### ISSUE TITLE
Swift 4 migration

### ISSUE THREAD

**Issue by pepibumur** [swift-xcode/xcodeproj#82]
## Context
Today the new version of Xcode is officially released together with Swift 4. We should migrate xcodeproj to the new version of Swift, including the `Package.swift` syntax.

## What
Migrate xcodeproj to Swift 4

## Proposal
- Migrate syntax.
- Migrate dependencies to their Swift 4 versions.

**Comment by pepibumur** [comment]
There was already a PR open trying to do the migration https://github.com/swift-xcode/xcodeproj/pull/42. We can maybe move on from there.

**Comment by artemnovichkov** [comment]
I see no warnings in xcodeproj. I can update Package manifest
